### [ 7TogkKeyShop ] ###

# Di buat Angga7Togk

# Di Buat karena Gabut :)
# Subrek Angga7Togk Tod

# Pengen Punya Ayang Cewek Animek Anjr

# Membutuhkan plugin EconomyAPI dan PiggyCrate
# Batas Tombol 1 - 10 Kalo Lebih Bakal Eror
1:
  Key:
    Name: "Common" # Nama Key Dari PiggyCrate
    Price: 1000 # Harga Key
  Button:
    Name: "§l§eCommon Key" # Nama Tombol
    Sub-Name: "Harga : 1k" # Nama Bawah 
2:
  Key:
    Name: "Legendary"
    Price: 5000
  Button:
    Name: "§l§eLegendary Key"
    Sub-Name: "Harga : 5k"
