### [ 7TogkKeyShop ] ###

# use § To Change Colors Text

# Need plugin EconomyAPI and PiggyCrate to launch this plugin

Title: "§l7TogkKeyShop"

1:
  Key:
    Name: "Common" # Key Name
    Price: 1000 # Price key
  Button:
    Name: "§l§eCommon Key" # Button Name
  Message:
    Succes: "§aSucces buy a key Common" # Success Message Buy A Key
    Failed: "§cYour money is not enough" # Failed Message Buy A Key
2:
  Key:
    Name: "Legendary"
    Price: 5000
  Button:
    Name: "§l§eLegendary Key"
  Message:
    Succes: "§aSucces buy a key Legendary"
    Failed: "§cYour money is not enough"
